name: DeathRespawn
main: com.deathrespawn.explorer.Main
version: 1.2
author: ExplorerVN
website: http://explorervn.ml/donate.php
depend: [Vault]
loadbefore: [Vault]

commands:
  deathrespawn:
    description: Show help display
    usage: /<command>
    aliases: dr
    
permissions:
  dr.respawn:
    description: Respawn permission
  dr.reload:
    description: Reload permission
